FROM node

WORKDIR /app

COPY elm-version elm-tooling.json ./
RUN sh elm-version setup /usr/local/bin && elm-version download

RUN ls -lahR ~/.elm/elm-tooling

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build
