FROM debian
RUN apt-get update && apt-get install -y curl
COPY elm-version elm-tooling.json ./
RUN sh elm-version setup /usr/local/bin && elm-version download
RUN ls -lahR ~/.elm/elm-tooling
RUN elm --version
RUN elm-format --help

