version: "3.3"
services:
  alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
  debian:
    build:
      context: .
      dockerfile: Dockerfile.debian
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
